name = "UAM"
author = "lhvy"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "99830f3ebb03f30325e3a88ee03e493bc0192de98049b3448df54a97e3cc744f"

[versions]
minecraft = "1.19.2"
quilt = "0.17.6"
