name = "UAM"
author = "lhvy"
version = "2.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cf52f2f7d7457ce290f4b53f72881a17c4d7a8dafc51860cfc6838caa2b8ec98"

[versions]
minecraft = "1.19.2"
quilt = "0.17.6"
