name = "UAM"
author = "lhvy"
version = "2.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "64dddb5d2e4464921661860ee653eefa713bb6e8a3e3d880ce6c925ce1da91eb"

[versions]
minecraft = "1.19.2"
quilt = "0.17.6"
