name = "UAM"
author = "lhvy"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "45a8ac0ad5fc0c97ec67607ae04222e677dcf4ccb8f3344a3155dddf9944524c"

[versions]
minecraft = "1.19"
quilt = "0.17.1-beta.4"
