name = "UAM"
author = "lhvy"
version = "1.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c3f64573ff9e571db1426922889960c51f31cdcf8d50e3a00b864276e78011b8"

[versions]
minecraft = "1.19"
quilt = "0.17.1-beta.4"
