name = "UAM"
author = "lhvy"
version = "1.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cf565ad00eb653a53b87738125f629890bbf2b8a9a68fb2b52eba50f1350405c"

[versions]
minecraft = "1.19"
quilt = "0.17.1-beta.4"
