name = "UAM"
author = "lhvy"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e0ab3cb157aa05845cd414e84ad3b1020234469b8908058d9a6faebf4c7a5c63"

[versions]
minecraft = "1.19"
quilt = "0.17.1-beta.4"
