name = "UAM"
author = "lhvy"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "077a6aa2af413071086437468917b49621eaeb1760bdc25f758894ffe15d3499"

[versions]
minecraft = "1.19"
quilt = "0.17.1-beta.4"
